jobs:
  build:
    docker:
      - image: cimg/python:3.9.6
    steps:
      - checkout
      - run:
          name: Building Virtual Environment
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install coverage
      - run:
          name: Running Tests
          command: |
            . venv/bin/activate
            CI=true coverage run \
              --omit='venv/*,NearBeach/tests/*,NearBeach/migrations/*,*/__init__.py,manage.py' \
              manage.py test
            coverage report
            coverage html
      # - run:
      #     name: Cypress End-2-End Tests
      #     command: npx cypress run --headless
      - store_test_results: # Upload test results for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: ~/project/NearBeach
          desintation: tr1
      - store_artifacts: # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: ~/project/NearBeach/htmlcov
          destination: tr1