version: 2
jobs:
  build: 
    working_directory: ~/NearBeach
    docker: # run the steps with Docker
      # CircleCI Python images available at: https://hub.docker.com/r/circleci/python/
      - image: circleci/python:3.6.4
        environment: # environment variables for primary container
          PIPENV_VENV_IN_PROJECT: true
    steps: # steps that comprise the `build` job
      - checkout # check out source code to working directory
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - run: sudo apt-get install build-essential python3-dev python3-pip python3-setuptools python3-wheel python3-cffi libcairo2 libpango-1.0-0 libpangocairo-1.0-0 libgdk-pixbuf2.0-0 libffi-dev shared-mime-info
      - run:
          name: Install pipenv and coverage
          command: |
            sudo pip3 install --upgrade pip
            sudo pip3 install pipenv coverage urllib3
            sudo pip3 install -r ./requirements.txt
            pipenv install
      - run:
          command: |
            pipenv run coverage run manage.py test
            pipenv run coverage report
            pipenv run coverage html
            ls -al
      - store_test_results: # Upload test results for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: ~/NearBeach/htmlcov
            pipenv run coverage html
      - store_artifacts: # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: ~/NearBeach/htmlcov
          destination: tr1
