name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hello and Welcome to NearBeach. Thank you for submitting your very first issue at NearBeach. We hope to continue to see your support :D'
        pr-message: 'YAY! Welcome to NearBeach. Thank you for your pull request, I will have a look at it soon. I do hope to see your continue support :D'
